name: Node CI

on:
  push:
    branches:
      - main
      - dev
      - open-source # test
      - feat/**
  pull_request:
    branches:
      - main
      - dev
      - open-source # test

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref || github.head_ref || github.ref_name }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Bootstrap project
      - name: deps-init
        run: npm run setup
      - name: lint
        run: npm run lint
      - name: build-ci
        run: npm run build:ci
        env:
          CI: true
